repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        name: Lint python (scraper)
        args: [--config, ./services/scraper/pyproject.toml, --fix, --exit-non-zero-on-fix]
        files: ^services/scraper/
      - id: ruff-check
        name: Lint python (api)
        args: [--config, ./services/api/pyproject.toml, --fix, --exit-non-zero-on-fix]
        files: ^services/api/
      - id: ruff-format
        name: Format python (scraper)
        args: [--config, ./services/scraper/pyproject.toml]
        files: ^services/scraper/
      - id: ruff-format
        name: Format python (api)
        args: [--config, ./services/api/pyproject.toml]
        files: ^services/api/
