services:
  realty-scheduler:
    container_name: realty-scheduler
    image: ghcr.io/diegoheer/realty-alerts:latest
    volumes:
      - ./queries:/queries  # Mount here to the folder with your query configs
      - ./data:/data # Mount here the folder where the sqlite and celery-beat database should be stored
    environment:
      - REDIS_URL=redis://realty-broker:6379/0
      - BROWSER_URL=ws://realty-browser:3000
    depends_on:
      realty-browser:
        condition: service_healthy
      realty-broker:
        condition: service_healthy
    healthcheck:
      test: celery -A tasks status
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s

  realty-browser:
    container_name: realty-browser
    image: mcr.microsoft.com/playwright:v1.53.0-noble
    command: /bin/sh -c "npx -y playwright@1.53.0 run-server --port 3000 --host 0.0.0.0"
    ports:
      - 3000:3000
    user: pwuser
    working_dir: /home/pwuser
    init: true
    healthcheck:
      test: curl -f localhost:3000
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 0s

  realty-broker:
    container_name: realty-broker
    image: redis:8.0.2
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 0s
