services:
  realty-ui:
    container_name: realty-ui
    image: ghcr.io/diegoheer/realty-alerts:latest
    entrypoint: ./django_setup.sh
    command: gunicorn core.wsgi:application --bind 0.0.0.0:9000
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
    env_file:
      - .prod.env
    depends_on:
      realty-database:
        condition: service_healthy
    healthcheck:
      test: curl -f localhost:9000
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s

  realty-scheduler:
    container_name: realty-scheduler
    image: ghcr.io/diegoheer/realty-alerts:latest
    command: celery -A core worker -B --pidfile=/tmp/celery-beat.pid
    volumes:
      - ./data:/data
    env_file:
      - .prod.env
    depends_on:
      realty-database:
        condition: service_healthy
      realty-browser:
        condition: service_healthy
      realty-broker:
        condition: service_healthy
    healthcheck:
      test: stat /tmp/celery-beat.pid || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s

  realty-database:
    container_name: realty-database
    image: postgres:17.6
    env_file:
      - .prod.env
    volumes:
      - realty-database-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s

  realty-browser:
    container_name: realty-browser
    image: mcr.microsoft.com/playwright:v1.53.0-noble
    command: /bin/sh -c "npx -y playwright@1.53.0 run-server --port 3000 --host 0.0.0.0"
    user: pwuser
    working_dir: /home/pwuser
    init: true
    healthcheck:
      test: curl -f localhost:3000
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 0s

  realty-broker:
    container_name: realty-broker
    image: redis:8.0.2
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 0s

volumes:
  realty-database-data:
