services:
  realty-alerts-scheduler:
    container_name: realty-alerts-scheduler
    image: ghcr.io/diegoheer/realty-alerts:latest
    volumes:
      - ./queries:/queries  # Mount here to the folder with your query configs
    environment:
      - REDIS_URL=redis://realty-alerts-broker:6379/0
    depends_on:
      realty-alerts-ntfy:
        condition: service_healthy
      realty-alerts-broker:
        condition: service_healthy

  realty-alerts-broker:
    container_name: realty-alerts-broker
    image: redis:8.0.2
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 0s

  realty-alerts-ntfy:
    container_name: realty-alerts-ntfy
    image: binwiederhier/ntfy:v2.12
    command:
      - serve
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - ntfy-data:/etc/ntfy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 0s

volumes:
  ntfy-data:
