# Generated by Django 6.0.4 on 2026-06-29 21:05

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("scraping", "0001_initial"),
        ("scraping", "0002_deadlisting_bag_id"),
        ("scraping", "0003_listing_status_values"),
        ("scraping", "0004_listing_status_changed_at"),
        ("scraping", "0005_rename_listing_to_residence"),
        ("scraping", "0006_rename_listingurl_to_listing"),
        ("scraping", "0007_alter_listing_residence"),
        ("scraping", "0008_listing_per_portal_fields_residence_aggregates"),
        ("scraping", "0009_pivot_residence_filter_index"),
        ("scraping", "0010_pr5_drop_legacy"),
        ("scraping", "0011_drop_legacy_residence_columns"),
        ("scraping", "0012_rename_scrape_run_and_scraped_at"),
        ("scraping", "0013_add_detail_scrape_run"),
        ("scraping", "0014_add_listing_detail_fields"),
        ("scraping", "0015_residence_coordinates"),
        ("scraping", "0016_residence_neighbourhood"),
        ("scraping", "0017_cbs_geo_stats"),
        ("scraping", "0018_split_fetched_at"),
        ("scraping", "0019_add_building_details_to_residence"),
        ("scraping", "0020_add_zoning_fields"),
        ("scraping", "0021_add_soil_status_fields"),
        ("scraping", "0022_add_foundation_risk_fields"),
        ("scraping", "0023_add_building_construction_type_fields"),
        ("scraping", "0024_add_foundation_risk_detail_fields"),
        ("scraping", "0025_rename_and_add_soil_fields"),
        ("scraping", "0026_residence_deal_type_and_indexes"),
        ("scraping", "0027_residence_listing_attrs"),
        ("scraping", "0028_backfill_residence_listing_attrs"),
        ("scraping", "0029_residence_price_per_m2"),
        ("scraping", "0030_residence_neighbourhood_code"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("geometry", models.JSONField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, null=True)),
                ("stats_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("geometry_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("stats_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "cities",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("geometry", models.JSONField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, null=True)),
                ("stats_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("geometry_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("stats_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="districts", to="scraping.city"
                    ),
                ),
            ],
            options={
                "db_table": "districts",
            },
        ),
        migrations.CreateModel(
            name="ListScrapeRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("listings_found", models.PositiveIntegerField(default=0)),
                ("new_listings_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "list_scrape_runs",
                "indexes": [models.Index(fields=["website", "started_at"], name="idx_list_scrape_runs_started")],
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("geometry", models.JSONField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, null=True)),
                ("stats_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("geometry_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("stats_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="neighborhoods", to="scraping.city"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighborhoods",
                        to="scraping.district",
                    ),
                ),
            ],
            options={
                "db_table": "neighborhoods",
            },
        ),
        migrations.CreateModel(
            name="Residence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bag_id", models.CharField(max_length=16, unique=True)),
                ("city", models.CharField(db_index=True, max_length=255)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("house_number", models.PositiveIntegerField(blank=True, null=True)),
                ("house_letter", models.CharField(blank=True, max_length=5, null=True)),
                ("house_number_suffix", models.CharField(blank=True, max_length=20, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("neighbourhood", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("neighbourhood_code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "Appartement"),
                            ("terraced", "Tussenwoning"),
                            ("corner", "Hoekwoning"),
                            ("semi_detached", "Twee-onder-één-kap"),
                            ("detached", "Vrijstaand"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "energy_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+++++", "A+++++"),
                            ("A++++", "A++++"),
                            ("A+++", "A+++"),
                            ("A++", "A++"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("energy_label_valid_until", models.DateField(blank=True, null=True)),
                (
                    "construction_type",
                    models.CharField(
                        blank=True,
                        choices=[("nieuwbouw", "Nieuwbouw"), ("bestaande_bouw", "Bestaande bouw")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("zoning_designation", models.CharField(blank=True, max_length=100, null=True)),
                ("zoning_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("soil_investigation_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("soil_contamination_status", models.CharField(blank=True, max_length=100, null=True)),
                ("soil_investigation_outcome", models.CharField(blank=True, max_length=100, null=True)),
                ("soil_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("foundation_risk_label", models.CharField(blank=True, max_length=100, null=True)),
                ("foundation_risk_soil_type", models.CharField(blank=True, max_length=100, null=True)),
                ("foundation_risk_pre1970_pct", models.FloatField(blank=True, null=True)),
                ("foundation_risk_description", models.TextField(blank=True, null=True)),
                ("foundation_risk_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("current_price_eur", models.BigIntegerField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[("new", "Nieuw"), ("sale_pending", "Verkocht onder voorbehoud"), ("sold", "Verkocht")],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "deal_type",
                    models.CharField(choices=[("sale", "Te koop"), ("rent", "Te huur")], default="sale", max_length=10),
                ),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("status_changed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("bedroom_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathroom_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("surface_area_m2", models.PositiveIntegerField(blank=True, null=True)),
                ("build_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "price_per_m2",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Cast(
                                "current_price_eur", output_field=models.FloatField()
                            ),
                            "/",
                            django.db.models.functions.comparison.NullIf("surface_area_m2", models.Value(0)),
                        ),
                        output_field=models.FloatField(),
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "residences",
                "indexes": [
                    models.Index(fields=["city", "current_price_eur"], name="idx_residences_filters"),
                    models.Index(fields=["deal_type", "-created_at", "-id"], name="idx_res_dealtype_created"),
                    models.Index(fields=["latitude", "longitude"], name="idx_res_lat_lon"),
                    models.Index(fields=["building_type"], name="idx_res_building_type"),
                    models.Index(fields=["energy_label"], name="idx_res_energy_label"),
                    models.Index(fields=["bedroom_count"], name="idx_res_bedroom_count"),
                    models.Index(fields=["bathroom_count"], name="idx_res_bathroom_count"),
                    models.Index(fields=["surface_area_m2"], name="idx_res_surface_area"),
                    models.Index(fields=["build_year"], name="idx_res_build_year"),
                    models.Index(fields=["price_per_m2"], name="idx_res_price_per_m2"),
                    models.Index(fields=["neighbourhood_code"], name="idx_res_neighbourhood_code"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("price", models.CharField(blank=True, max_length=100, null=True)),
                ("price_eur", models.BigIntegerField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Nieuw"), ("sale_pending", "Verkocht onder voorbehoud"), ("sold", "Verkocht")],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("list_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("detail_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("surface_area_m2", models.PositiveIntegerField(blank=True, null=True)),
                ("bedroom_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathroom_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("construction_period", models.CharField(blank=True, max_length=50, null=True)),
                ("energy_label", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("apartment", "Appartement"),
                            ("terraced", "Tussenwoning"),
                            ("corner", "Hoekwoning"),
                            ("semi_detached", "Twee-onder-één-kap"),
                            ("detached", "Vrijstaand"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "construction_type",
                    models.CharField(
                        blank=True,
                        choices=[("nieuwbouw", "Nieuwbouw"), ("bestaande_bouw", "Bestaande bouw")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("house_number", models.PositiveIntegerField(blank=True, null=True)),
                ("house_letter", models.CharField(blank=True, max_length=5, null=True)),
                ("house_number_suffix", models.CharField(blank=True, max_length=20, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bag_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("parse_failed", "Parse failed"),
                            ("missing_address", "Missing address"),
                            ("bag_no_match", "BAG no match"),
                            ("bag_ambiguous", "BAG ambiguous"),
                        ],
                        default="resolved",
                        max_length=20,
                    ),
                ),
                ("bag_failure_reason", models.TextField(blank=True, null=True)),
                ("bag_resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "residence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="scraping.residence",
                    ),
                ),
            ],
            options={
                "db_table": "listings",
            },
        ),
        migrations.CreateModel(
            name="DetailScrapeRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DISPATCHED", "Dispatched"), ("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=12,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_scrape_runs",
                        to="scraping.listing",
                    ),
                ),
            ],
            options={
                "db_table": "detail_scrape_runs",
                "indexes": [models.Index(fields=["listing", "dispatched_at"], name="idx_detail_runs_dispatched")],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["website", "first_seen_at"], name="idx_listings_website"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["bag_status"], name="idx_listings_bag_status"),
        ),
    ]
