# Generated by Django 6.0.4 on 2026-05-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeadListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("detail_url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("house_number", models.PositiveIntegerField(blank=True, null=True)),
                ("house_letter", models.CharField(blank=True, max_length=5, null=True)),
                ("house_number_suffix", models.CharField(blank=True, max_length=20, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("parse_failed", "Parse failed"),
                            ("missing_postcode_and_street", "Missing postcode and street"),
                            ("bag_no_match", "BAG no match"),
                            ("bag_ambiguous", "BAG ambiguous"),
                        ],
                        max_length=40,
                    ),
                ),
                ("scraped_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dead_listings",
                "indexes": [
                    models.Index(fields=["website", "created_at"], name="idx_dead_listings_website"),
                    models.Index(fields=["reason", "created_at"], name="idx_dead_listings_reason"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bag_id", models.CharField(max_length=16, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("price_eur", models.BigIntegerField(blank=True, null=True)),
                ("city", models.CharField(db_index=True, max_length=255)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("house_number", models.PositiveIntegerField(blank=True, null=True)),
                ("house_letter", models.CharField(blank=True, max_length=5, null=True)),
                ("house_number_suffix", models.CharField(blank=True, max_length=20, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                ("property_type", models.CharField(blank=True, max_length=100, null=True)),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("area_sqm", models.FloatField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=10
                    ),
                ),
                ("scraped_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "listings",
                "indexes": [models.Index(fields=["city", "property_type", "price_eur"], name="idx_listings_filters")],
            },
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("listings_found", models.PositiveIntegerField(default=0)),
                ("new_properties_count", models.PositiveIntegerField(default=0)),
                ("new_listing_urls_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "scrape_runs",
                "indexes": [models.Index(fields=["website", "started_at"], name="idx_scrape_runs_started")],
            },
        ),
        migrations.CreateModel(
            name="ListingUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="listing_urls", to="scraping.listing"
                    ),
                ),
            ],
            options={
                "db_table": "listing_urls",
                "indexes": [models.Index(fields=["website", "first_seen_at"], name="idx_listing_urls_website")],
            },
        ),
    ]
