# Generated by Django 6.0.4 on 2026-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("detail_url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("price_cents", models.BigIntegerField(blank=True, null=True)),
                ("city", models.CharField(db_index=True, max_length=255)),
                ("property_type", models.CharField(blank=True, max_length=100, null=True)),
                ("bedrooms", models.PositiveIntegerField(blank=True, null=True)),
                ("area_sqm", models.FloatField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=10
                    ),
                ),
                ("scraped_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "listings",
                "indexes": [
                    models.Index(fields=["city", "property_type", "price_cents"], name="idx_listings_filters"),
                    models.Index(fields=["website", "created_at"], name="idx_listings_website_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("listings_found", models.PositiveIntegerField(default=0)),
                ("listings_new", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "scrape_runs",
                "indexes": [models.Index(fields=["website", "started_at"], name="idx_scrape_runs_started")],
            },
        ),
    ]
