# Generated by Django 6.0.4 on 2026-04-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="listing",
            name="idx_listings_filters",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="price_cents",
            new_name="price_eur",
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["city", "property_type", "price_eur"], name="idx_listings_filters"),
        ),
    ]
