# Generated by Django 6.0.4 on 2026-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0001_squashed_0030_residence_neighbourhood_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="election_stats",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="election_stats_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="election_stats",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="election_stats_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="election_stats",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="election_stats_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
