# Generated by Django 6.0.4 on 2026-04-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_rename_price_cents_to_price_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
