# Generated by Django 6.0.4 on 2026-07-11 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0002_add_election_stats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("app_version", models.CharField(blank=True, max_length=20)),
                (
                    "platform",
                    models.CharField(
                        blank=True, choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")], max_length=10
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        blank=True, choices=[("en", "English"), ("nl", "Dutch"), ("pt", "Portuguese")], max_length=5
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
