# Generated by Django 6.0.4 on 2026-05-03 23:19

from django.db import migrations, models


def _backfill_legacy_values(apps, schema_editor):
    Listing = apps.get_model("scraping", "Listing")
    Listing.objects.filter(status="active").update(status="new")
    Listing.objects.filter(status="archived").update(status="sold")


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0002_deadlisting_bag_id"),
    ]

    operations = [
        migrations.RunPython(_backfill_legacy_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[("new", "Nieuw"), ("sale_pending", "Verkocht onder voorbehoud"), ("sold", "Verkocht")],
                default="new",
                max_length=16,
            ),
        ),
    ]
