# Generated by Django 6.0.4 on 2026-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0003_alter_listing_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="house_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="house_number_suffix",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
