# Generated by Django 6.0.4 on 2026-05-03 23:53

from django.db import migrations, models
from django.db.models import F


def _backfill_status_changed_at(apps, schema_editor):
    Listing = apps.get_model("scraping", "Listing")
    Listing.objects.update(status_changed_at=F("updated_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0003_listing_status_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(_backfill_status_changed_at, migrations.RunPython.noop),
    ]
