# Generated by Django 6.0.4 on 2026-05-04 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0004_listing_status_changed_at"),
    ]

    # `migrations.RenameIndex` is a Django >= 4.1 op; ty / django-types stubs
    # don't list it yet, so each call carries `# ty: ignore[unresolved-attribute]`.
    operations = [
        migrations.RenameModel(
            old_name="DeadListing",
            new_name="DeadResidence",
        ),
        migrations.RenameModel(
            old_name="Listing",
            new_name="Residence",
        ),
        migrations.RenameField(
            model_name="scraperun",
            old_name="new_properties_count",
            new_name="new_residences_count",
        ),
        migrations.RenameIndex(  # ty: ignore[unresolved-attribute]
            model_name="deadresidence",
            new_name="idx_dead_residences_website",
            old_name="idx_dead_listings_website",
        ),
        migrations.RenameIndex(  # ty: ignore[unresolved-attribute]
            model_name="deadresidence",
            new_name="idx_dead_residences_reason",
            old_name="idx_dead_listings_reason",
        ),
        migrations.RenameIndex(  # ty: ignore[unresolved-attribute]
            model_name="residence",
            new_name="idx_residences_filters",
            old_name="idx_listings_filters",
        ),
        migrations.AlterModelTable(
            name="deadresidence",
            table="dead_residences",
        ),
        migrations.AlterModelTable(
            name="residence",
            table="residences",
        ),
    ]
