# Generated by Django 6.0.4 on 2026-05-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0005_add_bag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="house_letter",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
