# Generated by Django 6.0.4 on 2026-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0006_listing_house_letter"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadListing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "website",
                    models.CharField(
                        choices=[("funda", "Funda"), ("pararius", "Pararius"), ("vastgoed_nl", "VastgoedNL")],
                        max_length=20,
                    ),
                ),
                ("detail_url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("house_number", models.PositiveIntegerField(blank=True, null=True)),
                ("house_letter", models.CharField(blank=True, max_length=5, null=True)),
                ("house_number_suffix", models.CharField(blank=True, max_length=20, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                ("image_url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("parse_failed", "Parse failed"),
                            ("missing_postcode_and_street", "Missing postcode and street"),
                            ("bag_no_match", "BAG no match"),
                            ("bag_ambiguous", "BAG ambiguous"),
                        ],
                        max_length=40,
                    ),
                ),
                ("scraped_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dead_listings",
                "indexes": [
                    models.Index(fields=["website", "created_at"], name="idx_dead_listings_website"),
                    models.Index(fields=["reason", "created_at"], name="idx_dead_listings_reason"),
                ],
            },
        ),
    ]
