# Generated by Django 6.0.4 on 2026-05-06 09:14

import django.db.models.deletion
from django.db import migrations, models


def _seed_residence_aggregates(apps, schema_editor):
    """Seed the new reconciled-aggregate columns on Residence from the legacy
    per-portal columns so PR 2 can pivot reads to current_* without waiting for
    every residence to be re-scraped. Same-row column copy — no cross-table
    backfill (existing Listings keep NULL per-portal fields and will populate
    on next scrape)."""
    Residence = apps.get_model("scraping", "Residence")
    Residence.objects.update(
        current_price_eur=models.F("price_eur"),
        current_status=models.F("status"),
        last_scraped_at=models.F("scraped_at"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_alter_listing_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bag_failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bag_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bag_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('parse_failed', 'Parse failed'), ('missing_address', 'Missing address'), ('bag_no_match', 'BAG no match'), ('bag_ambiguous', 'BAG ambiguous')], default='resolved', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_letter',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_number_suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_eur',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('new', 'Nieuw'), ('sale_pending', 'Verkocht onder voorbehoud'), ('sold', 'Verkocht')], default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='current_price_eur',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='current_status',
            field=models.CharField(choices=[('new', 'Nieuw'), ('sale_pending', 'Verkocht onder voorbehoud'), ('sold', 'Verkocht')], default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='residence',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='scraping.residence'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['bag_status'], name='idx_listings_bag_status'),
        ),
        migrations.RunPython(_seed_residence_aggregates, migrations.RunPython.noop),
    ]
