# Generated by Django 6.0.4 on 2026-05-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_listing_per_portal_fields_residence_aggregates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='residence',
            name='idx_residences_filters',
        ),
        migrations.AddIndex(
            model_name='residence',
            index=models.Index(fields=['city', 'current_price_eur'], name='idx_residences_filters'),
        ),
    ]
