# Generated by Django 6.0.4 on 2026-05-06 21:59

from django.db import migrations

# DeadResidenceReason → BagStatus. The two enums diverge on naming
# (`missing_postcode_and_street` → `missing_address`); everything else maps
# straight across.
_REASON_TO_BAG_STATUS = {
    "parse_failed": "parse_failed",
    "missing_postcode_and_street": "missing_address",
    "bag_no_match": "bag_no_match",
    "bag_ambiguous": "bag_ambiguous",
}


def _migrate_dead_residences_to_listings(apps, schema_editor):
    """Convert any remaining DeadResidence rows into unresolved Listings so
    admin triage data isn't lost when the table drops below. URLs that
    already exist as Listings (e.g. previously promoted via the dead-promotion
    admin action) are skipped."""
    DeadResidence = apps.get_model("scraping", "DeadResidence")
    Listing = apps.get_model("scraping", "Listing")

    existing_urls = set(Listing.objects.values_list("url", flat=True))
    for dead in DeadResidence.objects.all():
        if dead.detail_url in existing_urls:
            continue
        Listing.objects.create(
            residence=None,
            website=dead.website,
            url=dead.detail_url,
            title=dead.title,
            price=dead.price,
            image_url=dead.image_url,
            street=dead.street,
            house_number=dead.house_number,
            house_letter=dead.house_letter,
            house_number_suffix=dead.house_number_suffix,
            postcode=dead.postcode,
            city=dead.city,
            scraped_at=dead.scraped_at,
            last_seen_at=dead.scraped_at,
            bag_status=_REASON_TO_BAG_STATUS[dead.reason],
            bag_failure_reason=f"Migrated from DeadResidence: {dead.reason}",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0009_pivot_residence_filter_index"),
    ]

    operations = [
        migrations.RunPython(_migrate_dead_residences_to_listings, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="deadresidence",
            name="idx_dead_residences_website",
        ),
        migrations.RemoveIndex(
            model_name="deadresidence",
            name="idx_dead_residences_reason",
        ),
        migrations.DeleteModel(
            name="DeadResidence",
        ),
    ]
