# Generated by Django 6.0.4 on 2026-05-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0010_pr5_drop_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='area_sqm',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='price',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='status',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='title',
        ),
        migrations.RemoveField(
            model_name='scraperun',
            name='new_residences_count',
        ),
    ]
