# Generated by Django 6.0.4 on 2026-06-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0014_add_listing_detail_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residence",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
