# Generated by Django 6.0.4 on 2026-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0015_residence_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="residence",
            name="neighbourhood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
