# Generated by Django 6.0.4 on 2026-06-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0017_cbs_geo_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='fetched_at',
        ),
        migrations.AddField(
            model_name='city',
            name='geometry_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='geometry_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='geometry_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='stats_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
