# Generated by Django 6.0.4 on 2026-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0019_add_building_details_to_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='zoning_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='zoning_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
