# Generated by Django 6.0.4 on 2026-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0020_add_zoning_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="soil_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residence",
            name="soil_wbb_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
