# Generated by Django 6.0.4 on 2026-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping", "0021_add_soil_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="foundation_risk_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="residence",
            name="foundation_risk_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
