# Generated by Django 6.0.4 on 2026-06-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0022_add_foundation_risk_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='building_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('apartment', 'Appartement'),
                    ('terraced', 'Tussenwoning'),
                    ('corner', 'Hoekwoning'),
                    ('semi_detached', 'Twee-onder-één-kap'),
                    ('detached', 'Vrijstaand'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='listing',
            name='construction_type',
            field=models.CharField(
                blank=True,
                choices=[('nieuwbouw', 'Nieuwbouw'), ('bestaande_bouw', 'Bestaande bouw')],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='residence',
            name='construction_type',
            field=models.CharField(
                blank=True,
                choices=[('nieuwbouw', 'Nieuwbouw'), ('bestaande_bouw', 'Bestaande bouw')],
                max_length=20,
                null=True,
            ),
        ),
    ]
