# Generated by Django 6.0.4 on 2026-06-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0023_add_building_construction_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='foundation_risk_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='foundation_risk_pre1970_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='foundation_risk_soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
