# Generated by Django 6.0.4 on 2026-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0024_add_foundation_risk_detail_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='soil_wbb_count',
            new_name='soil_investigation_count',
        ),
        migrations.AddField(
            model_name='residence',
            name='soil_contamination_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='residence',
            name='soil_investigation_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
