# Generated by Django 6.0.4 on 2026-06-27 20:06

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
from django.db.migrations.operations.models import AddIndex


class AddIndexConcurrentlyIfPostgres(AddIndexConcurrently):
    """CREATE INDEX CONCURRENTLY on PostgreSQL (CI + prod); a plain CREATE INDEX
    everywhere else. The local/test default backend is SQLite, which has no
    CONCURRENTLY and rejects the kwarg, so fall back to the standard AddIndex."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        else:
            AddIndex.database_forwards(self, app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)
        else:
            AddIndex.database_backwards(self, app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    # CREATE INDEX CONCURRENTLY cannot run inside a transaction, so the whole
    # migration is non-atomic. On PostgreSQL the indexes are built concurrently
    # to avoid holding an ACCESS EXCLUSIVE lock on `residences` during deploy.
    atomic = False

    dependencies = [
        ("scraping", "0025_rename_and_add_soil_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="residence",
            name="deal_type",
            field=models.CharField(choices=[("sale", "Te koop"), ("rent", "Te huur")], default="sale", max_length=10),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name="residence",
            index=models.Index(fields=["deal_type", "-created_at", "-id"], name="idx_res_dealtype_created"),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name="residence",
            index=models.Index(fields=["latitude", "longitude"], name="idx_res_lat_lon"),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name="residence",
            index=models.Index(fields=["building_type"], name="idx_res_building_type"),
        ),
        AddIndexConcurrentlyIfPostgres(
            model_name="residence",
            index=models.Index(fields=["energy_label"], name="idx_res_energy_label"),
        ),
    ]
