# Generated by Django 5.2.4 on 2025-08-30 12:16

import django.db.models.deletion
import enums
import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealtyQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ntfy_topic", models.CharField(max_length=255, validators=[ui.models._validate_ntfy_topic])),
                ("query_url", models.URLField(max_length=500, validators=[ui.models._validate_query_url])),
                ("max_listing_page_number", models.PositiveIntegerField(default=3)),
                (
                    "periodic_task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "realty queries",
            },
        ),
        migrations.CreateModel(
            name="RealtyResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "new"), ("updated", "updated"), ("notified", "notified")],
                        default=enums.QueryResultStatus["NEW"],
                    ),
                ),
                ("detail_url", models.URLField()),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="ui.realtyquery"
                    ),
                ),
            ],
            options={
                "unique_together": {("query", "detail_url")},
            },
        ),
    ]
