# Generated by Django 5.2.4 on 2025-08-12 04:30

import django.db.models.deletion
import enums
import ui.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealtyQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ntfy_topic", models.CharField(max_length=255, validators=[ui.models._validate_ntfy_topic])),
                ("cron_schedule", models.CharField(max_length=100, validators=[ui.models._validate_cron_schedule])),
                ("query_url", models.URLField(validators=[ui.models._validate_query_url])),
                ("max_listing_page_number", models.PositiveIntegerField(default=3)),
                ("notify_startup_of_app", models.BooleanField(default=True)),
                ("notify_if_no_new_listing", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RealtyResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "new"), ("UPDATED", "updated"), ("NOTIFIED", "notified")],
                        default=enums.QueryResultStatus["NEW"],
                    ),
                ),
                ("detail_url", models.URLField()),
                ("title", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="results", to="ui.realtyquery"
                    ),
                ),
            ],
        ),
    ]
