# Generated by Django 5.2.4 on 2025-08-16 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtyquery",
            name="notify_if_no_new_listing",
        ),
        migrations.RemoveField(
            model_name="realtyquery",
            name="notify_startup_of_app",
        ),
    ]
