# Generated by Django 5.2.4 on 2025-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtyquery",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
