# Generated by Django 5.2.4 on 2025-08-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtyresult',
            name='detail_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='realtyresult',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
