# Generated by Django 5.2.4 on 2025-08-31 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0002_alter_realtyresult_detail_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtyquery",
            options={"ordering": ["name"], "verbose_name_plural": "realty queries"},
        ),
        migrations.AlterModelOptions(
            name="realtyresult",
            options={"ordering": ["status"]},
        ),
    ]
