# Generated by Django 5.2.4 on 2025-09-08 20:48

import enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0003_alter_realtyquery_options_alter_realtyresult_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtyquery",
            options={"ordering": ["-updated_at", "-created_at"], "verbose_name_plural": "realty queries"},
        ),
        migrations.AlterField(
            model_name="realtyresult",
            name="status",
            field=models.CharField(
                choices=[("new", "new"), ("updated", "updated"), ("notified", "notified"), ("archived", "archived")],
                default=enums.QueryResultStatus["NEW"],
            ),
        ),
    ]
