# Generated by Django 5.2.4 on 2025-09-08 22:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0004_alter_realtyquery_options_alter_realtyresult_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtyquery",
            options={
                "ordering": ["-periodic_task__last_run_at", "-created_at"],
                "verbose_name_plural": "realty queries",
            },
        ),
    ]
