# Generated by Django 5.2.4 on 2025-09-08 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0005_alter_realtyquery_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtyquery",
            options={
                "ordering": ["-created_at", "-periodic_task__last_run_at"],
                "verbose_name_plural": "realty queries",
            },
        ),
    ]
