# Generated by Django 5.2.4 on 2025-09-08 23:00

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0007_alter_realtyquery_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtyquery",
            options={
                "ordering": [
                    models.OrderBy(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("periodic_task__last_run_at"), models.F("created_at")
                        ),
                        descending=True,
                    ),
                    "-created_at",
                ],
                "verbose_name_plural": "realty queries",
            },
        ),
    ]
