// AUTO-GENERATED by design/build-tokens.mjs — DO NOT EDIT.
// Regenerate with: npm run tokens:build

export const lightTheme = {
  "color": {
    "navy": {
      "100": "#d8e0ec",
      "200": "#b3c1d5",
      "300": "#8a9fbb",
      "400": "#617d9e",
      "500": "#3d5c82",
      "600": "#2d4a6b",
      "700": "#213a56",
      "800": "#182c45",
      "900": "#0f1e3f",
      "950": "#081329",
      "050": "#f0f3f8"
    },
    "gold": {
      "100": "#f5ebda",
      "200": "#e8d4b5",
      "300": "#dbbe93",
      "400": "#cdaa80",
      "500": "#b3926a",
      "600": "#997953",
      "700": "#7d6344",
      "800": "#624d36",
      "900": "#483828",
      "950": "#30251b",
      "050": "#fdf8f1"
    },
    "neutral": {
      "100": "#efede8",
      "200": "#dedbd6",
      "300": "#c8c4bd",
      "400": "#a9a49c",
      "500": "#8a857e",
      "600": "#6e6a63",
      "700": "#55524c",
      "800": "#3d3b37",
      "900": "#282724",
      "950": "#1a1917",
      "050": "#f8f6f3"
    },
    "green": {
      "500": "#059669",
      "900": "#065f46",
      "050": "#ecfdf5"
    },
    "red": {
      "500": "#dc2626",
      "900": "#991b1b",
      "050": "#fef2f2"
    },
    "amber": {
      "500": "#d97706",
      "900": "#92400e",
      "050": "#fffbeb"
    },
    "blue": {
      "500": "#2563eb",
      "900": "#1e40af",
      "050": "#eff6ff"
    },
    "white": "#ffffff",
    "black": "#000000"
  },
  "opacity": {
    "transparent": 0,
    "005": 0.05,
    "010": 0.1,
    "015": 0.15,
    "020": 0.2,
    "030": 0.3,
    "040": 0.4,
    "050": 0.5,
    "060": 0.6,
    "070": 0.7,
    "080": 0.8,
    "085": 0.85,
    "090": 0.9,
    "opaque": 1
  },
  "scale": {
    "100": 8,
    "150": 12,
    "200": 16,
    "250": 20,
    "300": 24,
    "400": 32,
    "500": 40,
    "600": 48,
    "800": 64,
    "1000": 80,
    "base": 8,
    "050": 4,
    "075": 6
  },
  "dimension": {
    "100": 8,
    "150": 12,
    "200": 16,
    "250": 20,
    "300": 24,
    "400": 32,
    "500": 40,
    "600": 48,
    "800": 64,
    "1000": 80,
    "050": 4,
    "075": 6
  },
  "space": {
    "100": 8,
    "150": 12,
    "200": 16,
    "250": 20,
    "300": 24,
    "400": 32,
    "500": 40,
    "600": 48,
    "800": 64,
    "1000": 80,
    "none": 0,
    "050": 4,
    "075": 6
  },
  "radius": {
    "100": 8,
    "150": 12,
    "200": 16,
    "300": 24,
    "none": 0,
    "050": 4,
    "full": 9999
  },
  "sizing": {
    "icon-sm": 16,
    "icon-md": 20,
    "icon-lg": 24,
    "touch-target": 48,
    "avatar-sm": 32,
    "avatar-md": 40,
    "avatar-lg": 64
  },
  "line": {
    "none": 0,
    "xs": 0.5,
    "sm": 1,
    "md": 2,
    "lg": 3
  },
  "font-family": {
    "default": "'Plus Jakarta Sans'",
    "mono": "'JetBrains Mono'"
  },
  "font-weight": {
    "regular": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700
  },
  "font-size": {
    "2xs": 10,
    "xs": 12,
    "sm": 14,
    "md": 16,
    "lg": 18,
    "xl": 20,
    "2xl": 24,
    "3xl": 30,
    "4xl": 36
  },
  "line-height": {
    "tight": 1.2,
    "normal": 1.5,
    "relaxed": 1.75
  },
  "shadow": {
    "color": "rgba(15, 30, 63, 0.12)",
    "color-strong": "rgba(15, 30, 63, 0.24)",
    "distance": {
      "x": 0,
      "y": 0
    },
    "outer": {
      "soft": {
        "xs": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 1
          },
          "shadowRadius": 2,
          "elevation": 2
        },
        "sm": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 2
          },
          "shadowRadius": 4,
          "elevation": 4
        },
        "md": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 4
          },
          "shadowRadius": 8,
          "elevation": 8
        },
        "lg": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 8
          },
          "shadowRadius": 16,
          "elevation": 16
        },
        "xl": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.24,
          "shadowOffset": {
            "width": 0,
            "height": 16
          },
          "shadowRadius": 32,
          "elevation": 32
        }
      },
      "hard": {
        "sm": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 2
          },
          "shadowRadius": 0,
          "elevation": 0
        },
        "md": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 4
          },
          "shadowRadius": 0,
          "elevation": 0
        }
      }
    }
  },
  "duration": {
    "instant": 50,
    "fast": 100,
    "normal": 200,
    "moderate": 300,
    "slow": 500,
    "slower": 700
  },
  "easing": {
    "default": "cubic-bezier(0.25, 0.1, 0.25, 1)",
    "in": "cubic-bezier(0.42, 0, 1, 1)",
    "out": "cubic-bezier(0, 0, 0.58, 1)",
    "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
    "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
    "snap": "cubic-bezier(0.2, 0, 0, 1)"
  },
  "accent": {
    "100": "#f5ebda",
    "200": "#e8d4b5",
    "300": "#dbbe93",
    "400": "#cdaa80",
    "500": "#b3926a",
    "600": "#997953",
    "700": "#7d6344",
    "800": "#624d36",
    "900": "#483828",
    "950": "#30251b",
    "050": "#fdf8f1"
  },
  "neutral": {
    "100": "#efede8",
    "200": "#dedbd6",
    "300": "#c8c4bd",
    "400": "#a9a49c",
    "500": "#8a857e",
    "600": "#6e6a63",
    "700": "#55524c",
    "800": "#3d3b37",
    "900": "#282724",
    "950": "#1a1917",
    "050": "#f8f6f3"
  },
  "primary": {
    "100": "#d8e0ec",
    "200": "#b3c1d5",
    "300": "#8a9fbb",
    "400": "#617d9e",
    "500": "#3d5c82",
    "600": "#2d4a6b",
    "700": "#213a56",
    "800": "#182c45",
    "900": "#0f1e3f",
    "950": "#081329",
    "050": "#f0f3f8"
  },
  "layerBase": {
    "background": "#efede8",
    "text": "#6e6a63",
    "border": "#dedbd6",
    "icon": "#6e6a63",
    "highlight": "#cdaa80"
  },
  "layerOne": {
    "background": "#ffffff",
    "text": "#55524c",
    "border": "#dedbd6",
    "icon": "#55524c"
  },
  "layerTwo": {
    "background": "#f8f6f3",
    "text": "#6e6a63",
    "border": "#dedbd6",
    "icon": "#6e6a63"
  },
  "heading": {
    "text": "#0f1e3f"
  },
  "divider": "#dedbd6",
  "link": {
    "default": "#2d4a6b",
    "hovered": "#3d5c82",
    "focused": "#3d5c82",
    "pressed": "#213a56"
  },
  "buttonPrimary": {
    "background": {
      "default": "#cdaa80",
      "hovered": "#b3926a",
      "focused": "#b3926a",
      "pressed": "#997953",
      "disabled": "#c8c4bd"
    },
    "text": {
      "default": "#30251b",
      "hovered": "#30251b",
      "focused": "#30251b",
      "pressed": "#30251b",
      "disabled": "#8a857e"
    },
    "border": {
      "default": "rgba(0, 0, 0, 0)",
      "hovered": "rgba(0, 0, 0, 0)",
      "focused": "rgba(0, 0, 0, 0)",
      "pressed": "rgba(0, 0, 0, 0)",
      "disabled": "rgba(0, 0, 0, 0)"
    },
    "icon": {
      "default": "#30251b",
      "hovered": "#30251b",
      "focused": "#30251b",
      "pressed": "#30251b",
      "disabled": "#8a857e"
    }
  },
  "buttonSecondary": {
    "background": {
      "default": "#213a56",
      "hovered": "#2d4a6b",
      "focused": "#2d4a6b",
      "pressed": "#182c45",
      "disabled": "#c8c4bd"
    },
    "text": {
      "default": "#f0f3f8",
      "hovered": "#f0f3f8",
      "focused": "#f0f3f8",
      "pressed": "#d8e0ec",
      "disabled": "#8a857e"
    },
    "border": {
      "default": "rgba(0, 0, 0, 0)",
      "hovered": "rgba(0, 0, 0, 0)",
      "focused": "rgba(0, 0, 0, 0)",
      "pressed": "rgba(0, 0, 0, 0)",
      "disabled": "rgba(0, 0, 0, 0)"
    },
    "icon": {
      "default": "#f0f3f8",
      "hovered": "#f0f3f8",
      "focused": "#f0f3f8",
      "pressed": "#d8e0ec",
      "disabled": "#8a857e"
    }
  },
  "input": {
    "background": "#ffffff",
    "text": "#3d3b37",
    "border": "#c8c4bd",
    "icon": "#3d3b37"
  },
  "feedback": {
    "success": {
      "background": "#ecfdf5",
      "text": "#065f46"
    },
    "error": {
      "background": "#fef2f2",
      "text": "#991b1b"
    },
    "warning": {
      "background": "#fffbeb",
      "text": "#92400e"
    },
    "info": {
      "background": "#eff6ff",
      "text": "#1e40af"
    }
  },
  "accessible": {
    "text-on-accent": "#30251b",
    "text-on-primary": "#f0f3f8",
    "text-on-surface": "#0f1e3f",
    "text-on-surface-secondary": "#55524c",
    "text-on-success": "#065f46",
    "text-on-error": "#991b1b",
    "text-on-warning": "#92400e",
    "text-on-info": "#1e40af"
  },
  "type": {
    "display": {
      "fontFamily": "PlusJakartaSans_700Bold",
      "fontSize": 36,
      "lineHeight": 43
    },
    "heading-one": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 30,
      "lineHeight": 36
    },
    "heading-two": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 24,
      "lineHeight": 29
    },
    "heading-three": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 20,
      "lineHeight": 24
    },
    "body": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 16,
      "lineHeight": 24
    },
    "body-small": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 14,
      "lineHeight": 21
    },
    "label": {
      "fontFamily": "PlusJakartaSans_500Medium",
      "fontSize": 14,
      "lineHeight": 17
    },
    "caption": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 12,
      "lineHeight": 18
    }
  }
} as const;

export const darkTheme = {
  "color": {
    "navy": {
      "100": "#d8e0ec",
      "200": "#b3c1d5",
      "300": "#8a9fbb",
      "400": "#617d9e",
      "500": "#3d5c82",
      "600": "#2d4a6b",
      "700": "#213a56",
      "800": "#182c45",
      "900": "#0f1e3f",
      "950": "#081329",
      "050": "#f0f3f8"
    },
    "gold": {
      "100": "#f5ebda",
      "200": "#e8d4b5",
      "300": "#dbbe93",
      "400": "#cdaa80",
      "500": "#b3926a",
      "600": "#997953",
      "700": "#7d6344",
      "800": "#624d36",
      "900": "#483828",
      "950": "#30251b",
      "050": "#fdf8f1"
    },
    "neutral": {
      "100": "#efede8",
      "200": "#dedbd6",
      "300": "#c8c4bd",
      "400": "#a9a49c",
      "500": "#8a857e",
      "600": "#6e6a63",
      "700": "#55524c",
      "800": "#3d3b37",
      "900": "#282724",
      "950": "#1a1917",
      "050": "#f8f6f3"
    },
    "green": {
      "500": "#059669",
      "900": "#065f46",
      "050": "#ecfdf5"
    },
    "red": {
      "500": "#dc2626",
      "900": "#991b1b",
      "050": "#fef2f2"
    },
    "amber": {
      "500": "#d97706",
      "900": "#92400e",
      "050": "#fffbeb"
    },
    "blue": {
      "500": "#2563eb",
      "900": "#1e40af",
      "050": "#eff6ff"
    },
    "white": "#ffffff",
    "black": "#000000"
  },
  "opacity": {
    "transparent": 0,
    "005": 0.05,
    "010": 0.1,
    "015": 0.15,
    "020": 0.2,
    "030": 0.3,
    "040": 0.4,
    "050": 0.5,
    "060": 0.6,
    "070": 0.7,
    "080": 0.8,
    "085": 0.85,
    "090": 0.9,
    "opaque": 1
  },
  "scale": {
    "100": 8,
    "150": 12,
    "200": 16,
    "250": 20,
    "300": 24,
    "400": 32,
    "500": 40,
    "600": 48,
    "800": 64,
    "1000": 80,
    "base": 8,
    "050": 4,
    "075": 6
  },
  "dimension": {
    "100": 8,
    "150": 12,
    "200": 16,
    "250": 20,
    "300": 24,
    "400": 32,
    "500": 40,
    "600": 48,
    "800": 64,
    "1000": 80,
    "050": 4,
    "075": 6
  },
  "space": {
    "100": 8,
    "150": 12,
    "200": 16,
    "250": 20,
    "300": 24,
    "400": 32,
    "500": 40,
    "600": 48,
    "800": 64,
    "1000": 80,
    "none": 0,
    "050": 4,
    "075": 6
  },
  "radius": {
    "100": 8,
    "150": 12,
    "200": 16,
    "300": 24,
    "none": 0,
    "050": 4,
    "full": 9999
  },
  "sizing": {
    "icon-sm": 16,
    "icon-md": 20,
    "icon-lg": 24,
    "touch-target": 48,
    "avatar-sm": 32,
    "avatar-md": 40,
    "avatar-lg": 64
  },
  "line": {
    "none": 0,
    "xs": 0.5,
    "sm": 1,
    "md": 2,
    "lg": 3
  },
  "font-family": {
    "default": "'Plus Jakarta Sans'",
    "mono": "'JetBrains Mono'"
  },
  "font-weight": {
    "regular": 400,
    "medium": 500,
    "semibold": 600,
    "bold": 700
  },
  "font-size": {
    "2xs": 10,
    "xs": 12,
    "sm": 14,
    "md": 16,
    "lg": 18,
    "xl": 20,
    "2xl": 24,
    "3xl": 30,
    "4xl": 36
  },
  "line-height": {
    "tight": 1.2,
    "normal": 1.5,
    "relaxed": 1.75
  },
  "shadow": {
    "color": "rgba(15, 30, 63, 0.12)",
    "color-strong": "rgba(15, 30, 63, 0.24)",
    "distance": {
      "x": 0,
      "y": 0
    },
    "outer": {
      "soft": {
        "xs": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 1
          },
          "shadowRadius": 2,
          "elevation": 2
        },
        "sm": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 2
          },
          "shadowRadius": 4,
          "elevation": 4
        },
        "md": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 4
          },
          "shadowRadius": 8,
          "elevation": 8
        },
        "lg": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 8
          },
          "shadowRadius": 16,
          "elevation": 16
        },
        "xl": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.24,
          "shadowOffset": {
            "width": 0,
            "height": 16
          },
          "shadowRadius": 32,
          "elevation": 32
        }
      },
      "hard": {
        "sm": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 2
          },
          "shadowRadius": 0,
          "elevation": 0
        },
        "md": {
          "shadowColor": "rgb(15, 30, 63)",
          "shadowOpacity": 0.12,
          "shadowOffset": {
            "width": 0,
            "height": 4
          },
          "shadowRadius": 0,
          "elevation": 0
        }
      }
    }
  },
  "duration": {
    "instant": 50,
    "fast": 100,
    "normal": 200,
    "moderate": 300,
    "slow": 500,
    "slower": 700
  },
  "easing": {
    "default": "cubic-bezier(0.25, 0.1, 0.25, 1)",
    "in": "cubic-bezier(0.42, 0, 1, 1)",
    "out": "cubic-bezier(0, 0, 0.58, 1)",
    "in-out": "cubic-bezier(0.42, 0, 0.58, 1)",
    "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
    "snap": "cubic-bezier(0.2, 0, 0, 1)"
  },
  "accent": {
    "100": "#f5ebda",
    "200": "#e8d4b5",
    "300": "#dbbe93",
    "400": "#cdaa80",
    "500": "#b3926a",
    "600": "#997953",
    "700": "#7d6344",
    "800": "#624d36",
    "900": "#483828",
    "950": "#30251b",
    "050": "#fdf8f1"
  },
  "neutral": {
    "100": "#efede8",
    "200": "#dedbd6",
    "300": "#c8c4bd",
    "400": "#a9a49c",
    "500": "#8a857e",
    "600": "#6e6a63",
    "700": "#55524c",
    "800": "#3d3b37",
    "900": "#282724",
    "950": "#1a1917",
    "050": "#f8f6f3"
  },
  "primary": {
    "100": "#d8e0ec",
    "200": "#b3c1d5",
    "300": "#8a9fbb",
    "400": "#617d9e",
    "500": "#3d5c82",
    "600": "#2d4a6b",
    "700": "#213a56",
    "800": "#182c45",
    "900": "#0f1e3f",
    "950": "#081329",
    "050": "#f0f3f8"
  },
  "layerBase": {
    "background": "#081329",
    "text": "#8a9fbb",
    "border": "#213a56",
    "icon": "#8a9fbb",
    "highlight": "#cdaa80"
  },
  "layerOne": {
    "background": "#182c45",
    "text": "#b3c1d5",
    "border": "#2d4a6b",
    "icon": "#b3c1d5"
  },
  "layerTwo": {
    "background": "#0f1e3f",
    "text": "#8a9fbb",
    "border": "#213a56",
    "icon": "#8a9fbb"
  },
  "heading": {
    "text": "#f0f3f8"
  },
  "divider": "#213a56",
  "link": {
    "default": "#dbbe93",
    "hovered": "#e8d4b5",
    "focused": "#e8d4b5",
    "pressed": "#cdaa80"
  },
  "buttonPrimary": {
    "background": {
      "default": "#cdaa80",
      "hovered": "#dbbe93",
      "focused": "#dbbe93",
      "pressed": "#b3926a",
      "disabled": "#213a56"
    },
    "text": {
      "default": "#30251b",
      "hovered": "#30251b",
      "focused": "#30251b",
      "pressed": "#30251b",
      "disabled": "#3d5c82"
    },
    "border": {
      "default": "rgba(0, 0, 0, 0)",
      "hovered": "rgba(0, 0, 0, 0)",
      "focused": "rgba(0, 0, 0, 0)",
      "pressed": "rgba(0, 0, 0, 0)",
      "disabled": "rgba(0, 0, 0, 0)"
    },
    "icon": {
      "default": "#30251b",
      "hovered": "#30251b",
      "focused": "#30251b",
      "pressed": "#30251b",
      "disabled": "#3d5c82"
    }
  },
  "buttonSecondary": {
    "background": {
      "default": "#182c45",
      "hovered": "#213a56",
      "focused": "#213a56",
      "pressed": "#0f1e3f",
      "disabled": "#182c45"
    },
    "text": {
      "default": "#dbbe93",
      "hovered": "#e8d4b5",
      "focused": "#e8d4b5",
      "pressed": "#f5ebda",
      "disabled": "#3d5c82"
    },
    "border": {
      "default": "#2d4a6b",
      "hovered": "#3d5c82",
      "focused": "#3d5c82",
      "pressed": "#213a56",
      "disabled": "#213a56"
    },
    "icon": {
      "default": "#dbbe93",
      "hovered": "#e8d4b5",
      "focused": "#e8d4b5",
      "pressed": "#f5ebda",
      "disabled": "#3d5c82"
    }
  },
  "input": {
    "background": "#0f1e3f",
    "text": "#b3c1d5",
    "border": "#2d4a6b",
    "icon": "#b3c1d5"
  },
  "feedback": {
    "success": {
      "background": "#065f46",
      "text": "#ecfdf5"
    },
    "error": {
      "background": "#991b1b",
      "text": "#fef2f2"
    },
    "warning": {
      "background": "#92400e",
      "text": "#fffbeb"
    },
    "info": {
      "background": "#1e40af",
      "text": "#eff6ff"
    }
  },
  "accessible": {
    "text-on-accent": "#30251b",
    "text-on-primary": "#f0f3f8",
    "text-on-surface": "#f0f3f8",
    "text-on-surface-secondary": "#b3c1d5",
    "text-on-success": "#ecfdf5",
    "text-on-error": "#fef2f2",
    "text-on-warning": "#fffbeb",
    "text-on-info": "#eff6ff"
  },
  "type": {
    "display": {
      "fontFamily": "PlusJakartaSans_700Bold",
      "fontSize": 36,
      "lineHeight": 43
    },
    "heading-one": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 30,
      "lineHeight": 36
    },
    "heading-two": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 24,
      "lineHeight": 29
    },
    "heading-three": {
      "fontFamily": "PlusJakartaSans_600SemiBold",
      "fontSize": 20,
      "lineHeight": 24
    },
    "body": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 16,
      "lineHeight": 24
    },
    "body-small": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 14,
      "lineHeight": 21
    },
    "label": {
      "fontFamily": "PlusJakartaSans_500Medium",
      "fontSize": 14,
      "lineHeight": 17
    },
    "caption": {
      "fontFamily": "PlusJakartaSans_400Regular",
      "fontSize": 12,
      "lineHeight": 18
    }
  }
} as const;
