import { promises as fs } from "node:fs";
import path from "node:path";
import StyleDictionary from "style-dictionary";
import { register, permutateThemes, expandTypesMap } from "@tokens-studio/sd-transforms";

const ROOT = path.dirname(new URL(import.meta.url).pathname);
const SETS = path.join(ROOT, "sets");

register(StyleDictionary);

const raw = JSON.parse(await fs.readFile(path.join(ROOT, "tokens.json"), "utf8"));
const manifest = JSON.parse(await fs.readFile(path.join(SETS, "_manifest.json"), "utf8"));

// permutateThemes -> { "<themeName>": ["Set A", "Set B", ...], ... }
const themes = permutateThemes(raw.$themes, { separator: "_" });

// Recursively turn an SD nested token tree into a plain {key: resolvedValue} object.
function plain(node) {
  if (node && typeof node === "object" && "value" in node) return node.value;
  if (node && typeof node === "object" && "$value" in node) return node.$value;
  const out = {};
  for (const k of Object.keys(node)) {
    if (k.startsWith("$") || k === "filePath" || k === "isSource" || k === "original" || k === "name" || k === "attributes" || k === "path") continue;
    const v = node[k];
    if (v && typeof v === "object") out[k] = plain(v);
  }
  return out;
}

// Build each theme, collecting its resolved nested object.
const built = {};
for (const [themeName, setNames] of Object.entries(themes)) {
  const source = setNames.map((n) => path.join(SETS, manifest[n])).filter(Boolean);
  const sd = new StyleDictionary({
    source,
    preprocessors: ["tokens-studio"],
    expand: { typesMap: expandTypesMap },
    platforms: {
      js: { transformGroup: "tokens-studio", transforms: ["name/camel"] },
    },
  });
  const platform = await sd.getPlatformTokens("js");
  built[themeName] = plain(platform.tokens);
}

console.log("Built themes:", Object.keys(built).join(", "));

// Map raw permutateThemes names (e.g. "Global_Realty AI_Light"/"..._Dark") to stable exports.
function exportNameFor(rawName) {
  if (/(^|_)Dark($|_)/i.test(rawName)) return "darkTheme";
  if (/(^|_)Light($|_)/i.test(rawName)) return "lightTheme";
  return null;
}

const remapped = {};
for (const [rawName, obj] of Object.entries(built)) {
  const exportName = exportNameFor(rawName);
  if (!exportName) {
    console.warn("Skipping theme with no light/dark mapping:", rawName);
    continue;
  }
  if (remapped[exportName]) {
    throw new Error(`Multiple themes mapped to ${exportName}; refine exportNameFor().`);
  }
  remapped[exportName] = obj;
}

if (!remapped.lightTheme || !remapped.darkTheme) {
  throw new Error(`Expected both lightTheme and darkTheme; got: ${Object.keys(remapped).join(", ")}`);
}

// Emit one TS module with stable, deterministic ordering.
const header =
  "// AUTO-GENERATED by design/build-tokens.mjs — DO NOT EDIT.\n" +
  "// Regenerate with: npm run tokens:build\n\n";
const body = ["lightTheme", "darkTheme"]
  .map((name) => `export const ${name} = ${JSON.stringify(remapped[name], null, 2)} as const;`)
  .join("\n\n");
await fs.writeFile(path.join(ROOT, "..", "src", "theme", "tokens.generated.ts"), header + body + "\n");
console.log("Wrote src/theme/tokens.generated.ts");
