---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${APP_NAME}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: ${APP_NAME} app environments
  sourceRepos:
    - https://github.com/${CONFIG_REPO}.git
  destinations:
    - namespace: "${APP_NAME}-*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
